# yamllint configuration to keep repository YAML consistent.
extends: default

rules:
  line-length:
    max: 160
    allow-non-breakable-words: true
  document-start: disable
  truthy:
    level: warning
  comments:
    min-spaces-from-content: 2
  trailing-spaces: enable
  new-line-at-end-of-file: enable
