global:
  scrape_interval: 15s
  evaluation_interval: 30s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - prometheus-metrics:9090
  - job_name: "prometheus-api"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - host.docker.internal:8000
