name: Offline Packaging

on:
  schedule:
    - cron: "0 3 * * 1" # Mondays at 03:00 UTC
  workflow_dispatch:

env:
  POETRY_HOME: ~/.poetry

jobs:
  refresh-wheelhouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry==2.2.0

      - name: Install project dependencies
        run: |
          poetry install --with pii --no-interaction --no-root

      - name: Run offline packaging orchestrator
        run: |
          poetry run python scripts/offline_package.py --skip-phase git

      - name: Upload wheelhouse artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vendor-artifacts
          path: |
            vendor/wheelhouse/**
            vendor/models/manifest.json
            vendor/images/manifest.json
            vendor/packaging-run.json
            vendor/CHECKSUMS.sha256
